# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Anudeep\GUI\calculator\outline.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(328, 565)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frameMain = QtWidgets.QFrame(self.centralwidget)
        self.frameMain.setGeometry(QtCore.QRect(0, -20, 340, 651))
        self.frameMain.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameMain.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameMain.setObjectName("frameMain")
        self.frame_2 = QtWidgets.QFrame(self.frameMain)
        self.frame_2.setGeometry(QtCore.QRect(0, 40, 330, 130))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout.setObjectName("gridLayout")
        self.textBrowser = QtWidgets.QTextBrowser(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.textBrowser.setFont(font)
        self.textBrowser.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout.addWidget(self.textBrowser, 0, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.frameMain)
        self.frame.setGeometry(QtCore.QRect(0, 140, 320, 431))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton_seven = QtWidgets.QPushButton(self.frame)
        self.pushButton_seven.setGeometry(QtCore.QRect(20, 180, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_seven.setFont(font)
        self.pushButton_seven.setObjectName("pushButton_seven")
        self.pushButton_nine = QtWidgets.QPushButton(self.frame)
        self.pushButton_nine.setGeometry(QtCore.QRect(160, 180, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_nine.setFont(font)
        self.pushButton_nine.setObjectName("pushButton_nine")
        self.pushButton_four = QtWidgets.QPushButton(self.frame)
        self.pushButton_four.setGeometry(QtCore.QRect(20, 240, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_four.setFont(font)
        self.pushButton_four.setObjectName("pushButton_four")
        self.pushButton_eight = QtWidgets.QPushButton(self.frame)
        self.pushButton_eight.setGeometry(QtCore.QRect(90, 180, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_eight.setFont(font)
        self.pushButton_eight.setObjectName("pushButton_eight")
        self.pushButton_six = QtWidgets.QPushButton(self.frame)
        self.pushButton_six.setGeometry(QtCore.QRect(160, 240, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_six.setFont(font)
        self.pushButton_six.setObjectName("pushButton_six")
        self.pushButton_five = QtWidgets.QPushButton(self.frame)
        self.pushButton_five.setGeometry(QtCore.QRect(90, 240, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_five.setFont(font)
        self.pushButton_five.setObjectName("pushButton_five")
        self.pushButton_three = QtWidgets.QPushButton(self.frame)
        self.pushButton_three.setGeometry(QtCore.QRect(160, 300, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_three.setFont(font)
        self.pushButton_three.setObjectName("pushButton_three")
        self.pushButton_one = QtWidgets.QPushButton(self.frame)
        self.pushButton_one.setGeometry(QtCore.QRect(20, 300, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_one.setFont(font)
        self.pushButton_one.setObjectName("pushButton_one")
        self.pushButton_two = QtWidgets.QPushButton(self.frame)
        self.pushButton_two.setGeometry(QtCore.QRect(90, 300, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_two.setFont(font)
        self.pushButton_two.setObjectName("pushButton_two")
        self.pushButton_equal = QtWidgets.QPushButton(self.frame)
        self.pushButton_equal.setGeometry(QtCore.QRect(240, 360, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_equal.setFont(font)
        self.pushButton_equal.setObjectName("pushButton_equal")
        self.pushButton_plus = QtWidgets.QPushButton(self.frame)
        self.pushButton_plus.setGeometry(QtCore.QRect(240, 240, 71, 120))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_plus.setFont(font)
        self.pushButton_plus.setObjectName("pushButton_plus")
        self.pushButton_close = QtWidgets.QPushButton(self.frame)
        self.pushButton_close.setGeometry(QtCore.QRect(20, 110, 70, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_close.setFont(font)
        self.pushButton_close.setObjectName("pushButton_close")
        self.pushButton_open = QtWidgets.QPushButton(self.frame)
        self.pushButton_open.setGeometry(QtCore.QRect(20, 50, 70, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_open.setFont(font)
        self.pushButton_open.setObjectName("pushButton_open")
        self.pushButton_div = QtWidgets.QPushButton(self.frame)
        self.pushButton_div.setGeometry(QtCore.QRect(90, 50, 70, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_div.setFont(font)
        self.pushButton_div.setObjectName("pushButton_div")
        self.pushButton_power = QtWidgets.QPushButton(self.frame)
        self.pushButton_power.setGeometry(QtCore.QRect(90, 110, 70, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_power.setFont(font)
        self.pushButton_power.setObjectName("pushButton_power")
        self.pushButton_minus = QtWidgets.QPushButton(self.frame)
        self.pushButton_minus.setGeometry(QtCore.QRect(160, 110, 70, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_minus.setFont(font)
        self.pushButton_minus.setObjectName("pushButton_minus")
        self.pushButton_back = QtWidgets.QPushButton(self.frame)
        self.pushButton_back.setGeometry(QtCore.QRect(240, 110, 70, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_back.setFont(font)
        self.pushButton_back.setObjectName("pushButton_back")
        self.pushButton_multi = QtWidgets.QPushButton(self.frame)
        self.pushButton_multi.setGeometry(QtCore.QRect(160, 50, 70, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_multi.setFont(font)
        self.pushButton_multi.setObjectName("pushButton_multi")
        self.pushButton_clear = QtWidgets.QPushButton(self.frame)
        self.pushButton_clear.setGeometry(QtCore.QRect(240, 50, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_clear.setFont(font)
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.pushButton_plusorminus = QtWidgets.QPushButton(self.frame)
        self.pushButton_plusorminus.setGeometry(QtCore.QRect(20, 360, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_plusorminus.setFont(font)
        self.pushButton_plusorminus.setObjectName("pushButton_plusorminus")
        self.pushButton_zero = QtWidgets.QPushButton(self.frame)
        self.pushButton_zero.setGeometry(QtCore.QRect(90, 360, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_zero.setFont(font)
        self.pushButton_zero.setObjectName("pushButton_zero")
        self.pushButton_dot = QtWidgets.QPushButton(self.frame)
        self.pushButton_dot.setGeometry(QtCore.QRect(160, 360, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_dot.setFont(font)
        self.pushButton_dot.setObjectName("pushButton_dot")
        self.pushButton_ans = QtWidgets.QPushButton(self.frame)
        self.pushButton_ans.setGeometry(QtCore.QRect(240, 180, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_ans.setFont(font)
        self.pushButton_ans.setObjectName("pushButton_ans")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 328, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"right\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.pushButton_seven.setText(_translate("MainWindow", "7"))
        self.pushButton_nine.setText(_translate("MainWindow", "9"))
        self.pushButton_four.setText(_translate("MainWindow", "4"))
        self.pushButton_eight.setText(_translate("MainWindow", "8"))
        self.pushButton_six.setText(_translate("MainWindow", "6"))
        self.pushButton_five.setText(_translate("MainWindow", "5"))
        self.pushButton_three.setText(_translate("MainWindow", "3"))
        self.pushButton_one.setText(_translate("MainWindow", "1"))
        self.pushButton_two.setText(_translate("MainWindow", "2"))
        self.pushButton_equal.setText(_translate("MainWindow", "="))
        self.pushButton_plus.setText(_translate("MainWindow", "+"))
        self.pushButton_close.setText(_translate("MainWindow", ")"))
        self.pushButton_open.setText(_translate("MainWindow", "("))
        self.pushButton_div.setText(_translate("MainWindow", "/"))
        self.pushButton_power.setText(_translate("MainWindow", "^"))
        self.pushButton_minus.setText(_translate("MainWindow", "-"))
        self.pushButton_back.setText(_translate("MainWindow", "BACK"))
        self.pushButton_multi.setText(_translate("MainWindow", "*"))
        self.pushButton_clear.setText(_translate("MainWindow", "CLEAR"))
        self.pushButton_plusorminus.setText(_translate("MainWindow", "+/-"))
        self.pushButton_zero.setText(_translate("MainWindow", "0"))
        self.pushButton_dot.setText(_translate("MainWindow", "."))
        self.pushButton_ans.setText(_translate("MainWindow", "Ans"))

